# Auto LineageOS Tree Generator Workflow - Advanced Version
# Developed by: jisan ff <ffjisan804@gmail.com>
# New GitHub Identity: frnwot <frnbuid2005@gmail.com>

name: Auto LineageOS Tree Generator

on:
  workflow_dispatch:
    inputs:
      DUMP_URL:
        description: 'ROM dump Git repository URL'
        required: true
        default: 'https://github.com/yourusername/device_dump_repo'
      DUMP_BRANCH:
        description: 'ROM dump branch name'
        required: true
        default: 'main'
      DEVICE_BRAND:
        description: 'Device manufacturer (e.g., xiaomi, realme)'
        required: true
        default: 'xiaomi'
      CODENAME:
        description: 'Device codename (e.g., daisy)'
        required: true
        default: 'daisy'
      GIT_NAME:
        description: 'Your GitHub username'
        required: true
        default: 'frnwot'
      GIT_EMAIL:
        description: 'Your GitHub email address'
        required: true
        default: 'frnbuid2005@gmail.com'

jobs:
  gen-tree:
    name: Create LineageOS compatible tree
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.LOS }}
      DU: ${{ github.event.inputs.DUMP_URL }}
      DUB: ${{ github.event.inputs.DUMP_BRANCH }}
      DB: ${{ github.event.inputs.DEVICE_BRAND }}
      CN: ${{ github.event.inputs.CODENAME }}
      GN: ${{ github.event.inputs.GIT_NAME }}
      GE: ${{ github.event.inputs.GIT_EMAIL }}

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y cpio python3 git curl

    - name: Install GitHub CLI
      run: |
        type -p gh || (
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
            sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && \
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg && \
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
            sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
          sudo apt update && \
          sudo apt install -y gh
        )

    - name: Authenticate with GitHub CLI (Token Only)
      run: echo "$GH_TOKEN" | gh auth login --with-token

    - name: Clone ROM Dump
      run: |
        mkdir -p ~/LOS-Generator && cd ~/LOS-Generator
        git clone "$DU" -b "$DUB" dump

    - name: Install AOSPDTGEN
      run: pip3 install aospdtgen

    - name: Generate LineageOS tree
      run: |
        cd ~/LOS-Generator/dump
        python3 -m aospdtgen .
        mv output ../output

    - name: Configure Git identity
      run: |
        git config --global user.name "$GN"
        git config --global user.email "$GE"

    - name: Push LineageOS tree to GitHub
      run: |
        cd ~/LOS-Generator/output
        git init
        git checkout -b lineage-$CN
        git add .
        git commit -m "$CN: LineageOS compatible device tree"
        gh repo create lineage_device_${DB}_${CN} \
          --public \
          --description "LineageOS compatible device tree for $CN." \
          --source=. \
          --remote=origin \
          --push

    - name: Job Complete
      run: echo "✅ Tree generation complete!"

# Example Usage:
# Trigger this workflow manually with the following inputs:
#   DUMP_URL=https://github.com/yourusername/device_dump_repo
#   DUMP_BRANCH=main
#   DEVICE_BRAND=xiaomi
#   CODENAME=daisy
#   GIT_NAME=frnwot
#   GIT_EMAIL=frnbuid2005@gmail.com
# Ensure a GitHub token with repo access is saved in your repo secrets as `LOS`
